// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace FrameWorkApp
{
	public partial class MenuScreen : UITableViewController
	{
		public MenuScreen (IntPtr handle) : base (handle)
		{
		}

		partial void backButton (NSObject sender)
		{
			DismissViewController(true,null);
		}
	
	}
}
