// This file has been autogenerated from parsing an Objective-C header file added in Xcode.
using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace FrameWorkApp
{
	public partial class StatsScreen : UIViewController
	{
		SDMFileManager fileManager = new SDMFileManager ();
		User currentUser;

		public StatsScreen (IntPtr handle) : base (handle)
		{
			currentUser = fileManager.readUserFile ();
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			totalDistanceLabel.Text = currentUser.TotalDistance.ToString ();
			totalNumberOfEventsLabel.Text = currentUser.TotalNumberOfEvents.ToString ();
			totalPointsLabel.Text = currentUser.TotalPoints.ToString ();
		}
	}
}